### ISSUE TITLE
Roadmap to stable release

### ISSUE THREAD

**Issue by nakib** [wavebitscientific/functional-fortran#28]
Hello, all!

Is there a roadmap to the first stable release? A wish list?

(By the way, I'm posting this as an issue since there is no way to start a discussion.)

Best,
Nakib

**Comment by milancurcic** [comment]
Hi, Nakib!

There's no roadmap. The API has not broken since the initial release.

Would you like to have a functional-fortran v1.0.0?

**Comment by nakib** [comment]
Hi Milan,

I would like to use functional-fortran as a library in my project, elphbolt. I was just curious to know if some major overhaul was in the plans or not.

Best,
Nakib

**Comment by milancurcic** [comment]
No overhaul or API changes are planned. It's largely in maintenance mode from my perspective, however if you have ideas on how to improve or add to it, that would be very welcome.

**Comment by nakib** [comment]
Sounds good, Milan!
