### ISSUE TITLE
Releases

### ISSUE THREAD

**Issue by rouson** [wavebitscientific/functional-fortran#7]
Is there a plan to produce tagged release versions?  I'm about to install functional-fortran in the next release of the Sourcery Institute Linux [virtual machine](www.sourceryinstitute.org/store).  I usually include version information in the installation path along with the compiler and compiler version, for example: `/opt/functional-fortran/1.0.0/gnu/6.3.0` and I often summarize my download/installation steps in a bash script in which I'd generally rather access a tar ball via `curl` or `wget`.  That makes it easier to insure that I'm getting the same thing every time I run the script.

**Comment by milancurcic** [comment]
Hi Damian,

I drafted a release here: https://github.com/wavebitscientific/functional-fortran/releases/tag/0.2.0

The original CMake file did not have install rules, so I added them (see https://github.com/wavebitscientific/functional-fortran/commit/6d49f060a148d0efb497f1d8dd38826c39cdbccd). You can use `-DCMAKE_INSTALL_PREFIX` to specify install directory.

Thank you for including this in your VM!

**Comment by zbeekman** [comment]
This issue can be closed now, yes?

**Comment by rouson** [comment]
yes
